#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "> brew bundle"
brew bundle

# Restore settings with Mackup
echo "> mackup restore"
mackup restore --force

# find the installers and run them iteratively
echo "> run installers"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
